#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_PR_01_Clinicas.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbClinica")]
	public partial class DataClasesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttbUsuario(tbUsuario instance);
    partial void UpdatetbUsuario(tbUsuario instance);
    partial void DeletetbUsuario(tbUsuario instance);
    partial void InserttbDetalleEntrada(tbDetalleEntrada instance);
    partial void UpdatetbDetalleEntrada(tbDetalleEntrada instance);
    partial void DeletetbDetalleEntrada(tbDetalleEntrada instance);
    partial void InserttbDetalleSalida(tbDetalleSalida instance);
    partial void UpdatetbDetalleSalida(tbDetalleSalida instance);
    partial void DeletetbDetalleSalida(tbDetalleSalida instance);
    partial void InserttbEntrada(tbEntrada instance);
    partial void UpdatetbEntrada(tbEntrada instance);
    partial void DeletetbEntrada(tbEntrada instance);
    partial void InserttbPaciente(tbPaciente instance);
    partial void UpdatetbPaciente(tbPaciente instance);
    partial void DeletetbPaciente(tbPaciente instance);
    partial void InserttbProducto(tbProducto instance);
    partial void UpdatetbProducto(tbProducto instance);
    partial void DeletetbProducto(tbProducto instance);
    partial void InserttbRotacion(tbRotacion instance);
    partial void UpdatetbRotacion(tbRotacion instance);
    partial void DeletetbRotacion(tbRotacion instance);
    partial void InserttbRotacionUsuario(tbRotacionUsuario instance);
    partial void UpdatetbRotacionUsuario(tbRotacionUsuario instance);
    partial void DeletetbRotacionUsuario(tbRotacionUsuario instance);
    partial void InserttbSalida(tbSalida instance);
    partial void UpdatetbSalida(tbSalida instance);
    partial void DeletetbSalida(tbSalida instance);
    partial void InserttbTipoSangre(tbTipoSangre instance);
    partial void UpdatetbTipoSangre(tbTipoSangre instance);
    partial void DeletetbTipoSangre(tbTipoSangre instance);
    partial void InserttbCategoria(tbCategoria instance);
    partial void UpdatetbCategoria(tbCategoria instance);
    partial void DeletetbCategoria(tbCategoria instance);
    partial void InserttbPresentacion(tbPresentacion instance);
    partial void UpdatetbPresentacion(tbPresentacion instance);
    partial void DeletetbPresentacion(tbPresentacion instance);
    #endregion
		
		public DataClasesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbClinicaConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbUsuario> tbUsuario
		{
			get
			{
				return this.GetTable<tbUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tbDetalleEntrada> tbDetalleEntrada
		{
			get
			{
				return this.GetTable<tbDetalleEntrada>();
			}
		}
		
		public System.Data.Linq.Table<tbDetalleSalida> tbDetalleSalida
		{
			get
			{
				return this.GetTable<tbDetalleSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbEntrada> tbEntrada
		{
			get
			{
				return this.GetTable<tbEntrada>();
			}
		}
		
		public System.Data.Linq.Table<tbPaciente> tbPaciente
		{
			get
			{
				return this.GetTable<tbPaciente>();
			}
		}
		
		public System.Data.Linq.Table<tbProducto> tbProducto
		{
			get
			{
				return this.GetTable<tbProducto>();
			}
		}
		
		public System.Data.Linq.Table<tbRotacion> tbRotacion
		{
			get
			{
				return this.GetTable<tbRotacion>();
			}
		}
		
		public System.Data.Linq.Table<tbRotacionUsuario> tbRotacionUsuario
		{
			get
			{
				return this.GetTable<tbRotacionUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tbSalida> tbSalida
		{
			get
			{
				return this.GetTable<tbSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbTipoSangre> tbTipoSangre
		{
			get
			{
				return this.GetTable<tbTipoSangre>();
			}
		}
		
		public System.Data.Linq.Table<tbCategoria> tbCategoria
		{
			get
			{
				return this.GetTable<tbCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tbPresentacion> tbPresentacion
		{
			get
			{
				return this.GetTable<tbPresentacion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logiar")]
		public ISingleResult<LogiarResult> Logiar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string contra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, contra);
			return ((ISingleResult<LogiarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.existencias", IsComposable=true)]
		public System.Nullable<int> existencias([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codProducto)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codProducto).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbUsuario")]
	public partial class tbUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codUsuario;
		
		private int _codTipoUsuario;
		
		private string _nombre;
		
		private string _dpi;
		
		private string _carnet;
		
		private System.DateTime _fechaNacimiento;
		
		private string _usuario;
		
		private string _password;
		
		private bool _estado;
		
		private EntitySet<tbRotacionUsuario> _tbRotacionUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodUsuarioChanging(int value);
    partial void OncodUsuarioChanged();
    partial void OncodTipoUsuarioChanging(int value);
    partial void OncodTipoUsuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndpiChanging(string value);
    partial void OndpiChanged();
    partial void OncarnetChanging(string value);
    partial void OncarnetChanged();
    partial void OnfechaNacimientoChanging(System.DateTime value);
    partial void OnfechaNacimientoChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public tbUsuario()
		{
			this._tbRotacionUsuario = new EntitySet<tbRotacionUsuario>(new Action<tbRotacionUsuario>(this.attach_tbRotacionUsuario), new Action<tbRotacionUsuario>(this.detach_tbRotacionUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codUsuario
		{
			get
			{
				return this._codUsuario;
			}
			set
			{
				if ((this._codUsuario != value))
				{
					this.OncodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._codUsuario = value;
					this.SendPropertyChanged("codUsuario");
					this.OncodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoUsuario", DbType="Int NOT NULL")]
		public int codTipoUsuario
		{
			get
			{
				return this._codTipoUsuario;
			}
			set
			{
				if ((this._codTipoUsuario != value))
				{
					this.OncodTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._codTipoUsuario = value;
					this.SendPropertyChanged("codTipoUsuario");
					this.OncodTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string dpi
		{
			get
			{
				return this._dpi;
			}
			set
			{
				if ((this._dpi != value))
				{
					this.OndpiChanging(value);
					this.SendPropertyChanging();
					this._dpi = value;
					this.SendPropertyChanged("dpi");
					this.OndpiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnet", DbType="VarChar(13)")]
		public string carnet
		{
			get
			{
				return this._carnet;
			}
			set
			{
				if ((this._carnet != value))
				{
					this.OncarnetChanging(value);
					this.SendPropertyChanging();
					this._carnet = value;
					this.SendPropertyChanged("carnet");
					this.OncarnetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUsuario_tbRotacionUsuario", Storage="_tbRotacionUsuario", ThisKey="codUsuario", OtherKey="codUsuario")]
		public EntitySet<tbRotacionUsuario> tbRotacionUsuario
		{
			get
			{
				return this._tbRotacionUsuario;
			}
			set
			{
				this._tbRotacionUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbRotacionUsuario(tbRotacionUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tbUsuario = this;
		}
		
		private void detach_tbRotacionUsuario(tbRotacionUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tbUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetalleEntrada")]
	public partial class tbDetalleEntrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codEntrada;
		
		private int _codProducto;
		
		private System.Nullable<int> _cantidad;
		
		private EntityRef<tbEntrada> _tbEntrada;
		
		private EntityRef<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodEntradaChanging(int value);
    partial void OncodEntradaChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public tbDetalleEntrada()
		{
			this._tbEntrada = default(EntityRef<tbEntrada>);
			this._tbProducto = default(EntityRef<tbProducto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEntrada", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codEntrada
		{
			get
			{
				return this._codEntrada;
			}
			set
			{
				if ((this._codEntrada != value))
				{
					if (this._tbEntrada.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodEntradaChanging(value);
					this.SendPropertyChanging();
					this._codEntrada = value;
					this.SendPropertyChanged("codEntrada");
					this.OncodEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					if (this._tbProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbEntrada_tbDetalleEntrada", Storage="_tbEntrada", ThisKey="codEntrada", OtherKey="codEntrada", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbEntrada tbEntrada
		{
			get
			{
				return this._tbEntrada.Entity;
			}
			set
			{
				tbEntrada previousValue = this._tbEntrada.Entity;
				if (((previousValue != value) 
							|| (this._tbEntrada.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbEntrada.Entity = null;
						previousValue.tbDetalleEntrada.Remove(this);
					}
					this._tbEntrada.Entity = value;
					if ((value != null))
					{
						value.tbDetalleEntrada.Add(this);
						this._codEntrada = value.codEntrada;
					}
					else
					{
						this._codEntrada = default(int);
					}
					this.SendPropertyChanged("tbEntrada");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbDetalleEntrada", Storage="_tbProducto", ThisKey="codProducto", OtherKey="codProducto", IsForeignKey=true)]
		public tbProducto tbProducto
		{
			get
			{
				return this._tbProducto.Entity;
			}
			set
			{
				tbProducto previousValue = this._tbProducto.Entity;
				if (((previousValue != value) 
							|| (this._tbProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProducto.Entity = null;
						previousValue.tbDetalleEntrada.Remove(this);
					}
					this._tbProducto.Entity = value;
					if ((value != null))
					{
						value.tbDetalleEntrada.Add(this);
						this._codProducto = value.codProducto;
					}
					else
					{
						this._codProducto = default(int);
					}
					this.SendPropertyChanged("tbProducto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetalleSalida")]
	public partial class tbDetalleSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codSalida;
		
		private int _codProducto;
		
		private System.Nullable<int> _cantidad;
		
		private EntityRef<tbProducto> _tbProducto;
		
		private EntityRef<tbSalida> _tbSalida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodSalidaChanging(int value);
    partial void OncodSalidaChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public tbDetalleSalida()
		{
			this._tbProducto = default(EntityRef<tbProducto>);
			this._tbSalida = default(EntityRef<tbSalida>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSalida", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codSalida
		{
			get
			{
				return this._codSalida;
			}
			set
			{
				if ((this._codSalida != value))
				{
					if (this._tbSalida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodSalidaChanging(value);
					this.SendPropertyChanging();
					this._codSalida = value;
					this.SendPropertyChanged("codSalida");
					this.OncodSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					if (this._tbProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbDetalleSalida", Storage="_tbProducto", ThisKey="codProducto", OtherKey="codProducto", IsForeignKey=true)]
		public tbProducto tbProducto
		{
			get
			{
				return this._tbProducto.Entity;
			}
			set
			{
				tbProducto previousValue = this._tbProducto.Entity;
				if (((previousValue != value) 
							|| (this._tbProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProducto.Entity = null;
						previousValue.tbDetalleSalida.Remove(this);
					}
					this._tbProducto.Entity = value;
					if ((value != null))
					{
						value.tbDetalleSalida.Add(this);
						this._codProducto = value.codProducto;
					}
					else
					{
						this._codProducto = default(int);
					}
					this.SendPropertyChanged("tbProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSalida_tbDetalleSalida", Storage="_tbSalida", ThisKey="codSalida", OtherKey="codSalida", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbSalida tbSalida
		{
			get
			{
				return this._tbSalida.Entity;
			}
			set
			{
				tbSalida previousValue = this._tbSalida.Entity;
				if (((previousValue != value) 
							|| (this._tbSalida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSalida.Entity = null;
						previousValue.tbDetalleSalida.Remove(this);
					}
					this._tbSalida.Entity = value;
					if ((value != null))
					{
						value.tbDetalleSalida.Add(this);
						this._codSalida = value.codSalida;
					}
					else
					{
						this._codSalida = default(int);
					}
					this.SendPropertyChanged("tbSalida");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEntrada")]
	public partial class tbEntrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codEntrada;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaEntrada;
		
		private EntitySet<tbDetalleEntrada> _tbDetalleEntrada;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodEntradaChanging(int value);
    partial void OncodEntradaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntradaChanged();
    #endregion
		
		public tbEntrada()
		{
			this._tbDetalleEntrada = new EntitySet<tbDetalleEntrada>(new Action<tbDetalleEntrada>(this.attach_tbDetalleEntrada), new Action<tbDetalleEntrada>(this.detach_tbDetalleEntrada));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEntrada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codEntrada
		{
			get
			{
				return this._codEntrada;
			}
			set
			{
				if ((this._codEntrada != value))
				{
					this.OncodEntradaChanging(value);
					this.SendPropertyChanging();
					this._codEntrada = value;
					this.SendPropertyChanged("codEntrada");
					this.OncodEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntrada", DbType="Date")]
		public System.Nullable<System.DateTime> fechaEntrada
		{
			get
			{
				return this._fechaEntrada;
			}
			set
			{
				if ((this._fechaEntrada != value))
				{
					this.OnfechaEntradaChanging(value);
					this.SendPropertyChanging();
					this._fechaEntrada = value;
					this.SendPropertyChanged("fechaEntrada");
					this.OnfechaEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbEntrada_tbDetalleEntrada", Storage="_tbDetalleEntrada", ThisKey="codEntrada", OtherKey="codEntrada")]
		public EntitySet<tbDetalleEntrada> tbDetalleEntrada
		{
			get
			{
				return this._tbDetalleEntrada;
			}
			set
			{
				this._tbDetalleEntrada.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetalleEntrada(tbDetalleEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbEntrada = this;
		}
		
		private void detach_tbDetalleEntrada(tbDetalleEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbEntrada = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPaciente")]
	public partial class tbPaciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPaciente;
		
		private string _nombre;
		
		private System.Nullable<bool> _genero;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private System.Nullable<bool> _estadoCivil;
		
		private string _residencia;
		
		private string _procedencia;
		
		private string _religion;
		
		private string _profesion;
		
		private string _razaEtnia;
		
		private string _escolaridad;
		
		private System.Nullable<int> _codTipoSangre;
		
		private EntityRef<tbTipoSangre> _tbTipoSangre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPacienteChanging(int value);
    partial void OncodPacienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OngeneroChanging(System.Nullable<bool> value);
    partial void OngeneroChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OnestadoCivilChanging(System.Nullable<bool> value);
    partial void OnestadoCivilChanged();
    partial void OnresidenciaChanging(string value);
    partial void OnresidenciaChanged();
    partial void OnprocedenciaChanging(string value);
    partial void OnprocedenciaChanged();
    partial void OnreligionChanging(string value);
    partial void OnreligionChanged();
    partial void OnprofesionChanging(string value);
    partial void OnprofesionChanged();
    partial void OnrazaEtniaChanging(string value);
    partial void OnrazaEtniaChanged();
    partial void OnescolaridadChanging(string value);
    partial void OnescolaridadChanged();
    partial void OncodTipoSangreChanging(System.Nullable<int> value);
    partial void OncodTipoSangreChanged();
    #endregion
		
		public tbPaciente()
		{
			this._tbTipoSangre = default(EntityRef<tbTipoSangre>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPaciente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPaciente
		{
			get
			{
				return this._codPaciente;
			}
			set
			{
				if ((this._codPaciente != value))
				{
					this.OncodPacienteChanging(value);
					this.SendPropertyChanging();
					this._codPaciente = value;
					this.SendPropertyChanged("codPaciente");
					this.OncodPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="Bit")]
		public System.Nullable<bool> genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this.OngeneroChanging(value);
					this.SendPropertyChanging();
					this._genero = value;
					this.SendPropertyChanged("genero");
					this.OngeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoCivil", DbType="Bit")]
		public System.Nullable<bool> estadoCivil
		{
			get
			{
				return this._estadoCivil;
			}
			set
			{
				if ((this._estadoCivil != value))
				{
					this.OnestadoCivilChanging(value);
					this.SendPropertyChanging();
					this._estadoCivil = value;
					this.SendPropertyChanged("estadoCivil");
					this.OnestadoCivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_residencia", DbType="VarChar(50)")]
		public string residencia
		{
			get
			{
				return this._residencia;
			}
			set
			{
				if ((this._residencia != value))
				{
					this.OnresidenciaChanging(value);
					this.SendPropertyChanging();
					this._residencia = value;
					this.SendPropertyChanged("residencia");
					this.OnresidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedencia", DbType="VarChar(50)")]
		public string procedencia
		{
			get
			{
				return this._procedencia;
			}
			set
			{
				if ((this._procedencia != value))
				{
					this.OnprocedenciaChanging(value);
					this.SendPropertyChanging();
					this._procedencia = value;
					this.SendPropertyChanged("procedencia");
					this.OnprocedenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_religion", DbType="VarChar(50)")]
		public string religion
		{
			get
			{
				return this._religion;
			}
			set
			{
				if ((this._religion != value))
				{
					this.OnreligionChanging(value);
					this.SendPropertyChanging();
					this._religion = value;
					this.SendPropertyChanged("religion");
					this.OnreligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesion", DbType="VarChar(50)")]
		public string profesion
		{
			get
			{
				return this._profesion;
			}
			set
			{
				if ((this._profesion != value))
				{
					this.OnprofesionChanging(value);
					this.SendPropertyChanging();
					this._profesion = value;
					this.SendPropertyChanged("profesion");
					this.OnprofesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razaEtnia", DbType="VarChar(50)")]
		public string razaEtnia
		{
			get
			{
				return this._razaEtnia;
			}
			set
			{
				if ((this._razaEtnia != value))
				{
					this.OnrazaEtniaChanging(value);
					this.SendPropertyChanging();
					this._razaEtnia = value;
					this.SendPropertyChanged("razaEtnia");
					this.OnrazaEtniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_escolaridad", DbType="VarChar(50)")]
		public string escolaridad
		{
			get
			{
				return this._escolaridad;
			}
			set
			{
				if ((this._escolaridad != value))
				{
					this.OnescolaridadChanging(value);
					this.SendPropertyChanging();
					this._escolaridad = value;
					this.SendPropertyChanged("escolaridad");
					this.OnescolaridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoSangre", DbType="Int")]
		public System.Nullable<int> codTipoSangre
		{
			get
			{
				return this._codTipoSangre;
			}
			set
			{
				if ((this._codTipoSangre != value))
				{
					if (this._tbTipoSangre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodTipoSangreChanging(value);
					this.SendPropertyChanging();
					this._codTipoSangre = value;
					this.SendPropertyChanged("codTipoSangre");
					this.OncodTipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbTipoSangre_tbPaciente", Storage="_tbTipoSangre", ThisKey="codTipoSangre", OtherKey="codTipoSangre", IsForeignKey=true)]
		public tbTipoSangre tbTipoSangre
		{
			get
			{
				return this._tbTipoSangre.Entity;
			}
			set
			{
				tbTipoSangre previousValue = this._tbTipoSangre.Entity;
				if (((previousValue != value) 
							|| (this._tbTipoSangre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTipoSangre.Entity = null;
						previousValue.tbPaciente.Remove(this);
					}
					this._tbTipoSangre.Entity = value;
					if ((value != null))
					{
						value.tbPaciente.Add(this);
						this._codTipoSangre = value.codTipoSangre;
					}
					else
					{
						this._codTipoSangre = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbTipoSangre");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProducto")]
	public partial class tbProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProducto;
		
		private System.Nullable<int> _codCategoria;
		
		private System.Nullable<int> _codPresentacion;
		
		private string _producto;
		
		private System.Nullable<decimal> _dosis;
		
		private System.Nullable<int> _codVolumen;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<tbDetalleEntrada> _tbDetalleEntrada;
		
		private EntitySet<tbDetalleSalida> _tbDetalleSalida;
		
		private EntityRef<tbCategoria> _tbCategoria;
		
		private EntityRef<tbPresentacion> _tbPresentacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncodCategoriaChanging(System.Nullable<int> value);
    partial void OncodCategoriaChanged();
    partial void OncodPresentacionChanging(System.Nullable<int> value);
    partial void OncodPresentacionChanged();
    partial void OnproductoChanging(string value);
    partial void OnproductoChanged();
    partial void OndosisChanging(System.Nullable<decimal> value);
    partial void OndosisChanged();
    partial void OncodVolumenChanging(System.Nullable<int> value);
    partial void OncodVolumenChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public tbProducto()
		{
			this._tbDetalleEntrada = new EntitySet<tbDetalleEntrada>(new Action<tbDetalleEntrada>(this.attach_tbDetalleEntrada), new Action<tbDetalleEntrada>(this.detach_tbDetalleEntrada));
			this._tbDetalleSalida = new EntitySet<tbDetalleSalida>(new Action<tbDetalleSalida>(this.attach_tbDetalleSalida), new Action<tbDetalleSalida>(this.detach_tbDetalleSalida));
			this._tbCategoria = default(EntityRef<tbCategoria>);
			this._tbPresentacion = default(EntityRef<tbPresentacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", DbType="Int")]
		public System.Nullable<int> codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					if (this._tbCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", DbType="Int")]
		public System.Nullable<int> codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					if (this._tbPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(50)")]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this.OnproductoChanging(value);
					this.SendPropertyChanging();
					this._producto = value;
					this.SendPropertyChanged("producto");
					this.OnproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosis", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> dosis
		{
			get
			{
				return this._dosis;
			}
			set
			{
				if ((this._dosis != value))
				{
					this.OndosisChanging(value);
					this.SendPropertyChanging();
					this._dosis = value;
					this.SendPropertyChanged("dosis");
					this.OndosisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codVolumen", DbType="Int")]
		public System.Nullable<int> codVolumen
		{
			get
			{
				return this._codVolumen;
			}
			set
			{
				if ((this._codVolumen != value))
				{
					this.OncodVolumenChanging(value);
					this.SendPropertyChanging();
					this._codVolumen = value;
					this.SendPropertyChanged("codVolumen");
					this.OncodVolumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbDetalleEntrada", Storage="_tbDetalleEntrada", ThisKey="codProducto", OtherKey="codProducto")]
		public EntitySet<tbDetalleEntrada> tbDetalleEntrada
		{
			get
			{
				return this._tbDetalleEntrada;
			}
			set
			{
				this._tbDetalleEntrada.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbDetalleSalida", Storage="_tbDetalleSalida", ThisKey="codProducto", OtherKey="codProducto")]
		public EntitySet<tbDetalleSalida> tbDetalleSalida
		{
			get
			{
				return this._tbDetalleSalida;
			}
			set
			{
				this._tbDetalleSalida.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbCategoria", ThisKey="codCategoria", OtherKey="codCategoria", IsForeignKey=true)]
		public tbCategoria tbCategoria
		{
			get
			{
				return this._tbCategoria.Entity;
			}
			set
			{
				tbCategoria previousValue = this._tbCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tbCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCategoria.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbCategoria.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codCategoria = value.codCategoria;
					}
					else
					{
						this._codCategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbCategoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProducto", Storage="_tbPresentacion", ThisKey="codPresentacion", OtherKey="codPresentacion", IsForeignKey=true)]
		public tbPresentacion tbPresentacion
		{
			get
			{
				return this._tbPresentacion.Entity;
			}
			set
			{
				tbPresentacion previousValue = this._tbPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPresentacion.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codPresentacion = value.codPresentacion;
					}
					else
					{
						this._codPresentacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbPresentacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetalleEntrada(tbDetalleEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = this;
		}
		
		private void detach_tbDetalleEntrada(tbDetalleEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = null;
		}
		
		private void attach_tbDetalleSalida(tbDetalleSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = this;
		}
		
		private void detach_tbDetalleSalida(tbDetalleSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbRotacion")]
	public partial class tbRotacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codRotacion;
		
		private System.Nullable<System.DateTime> _fechaInicio;
		
		private System.Nullable<System.DateTime> _fechaFinal;
		
		private EntitySet<tbRotacionUsuario> _tbRotacionUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodRotacionChanging(int value);
    partial void OncodRotacionChanged();
    partial void OnfechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaInicioChanged();
    partial void OnfechaFinalChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaFinalChanged();
    #endregion
		
		public tbRotacion()
		{
			this._tbRotacionUsuario = new EntitySet<tbRotacionUsuario>(new Action<tbRotacionUsuario>(this.attach_tbRotacionUsuario), new Action<tbRotacionUsuario>(this.detach_tbRotacionUsuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRotacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codRotacion
		{
			get
			{
				return this._codRotacion;
			}
			set
			{
				if ((this._codRotacion != value))
				{
					this.OncodRotacionChanging(value);
					this.SendPropertyChanging();
					this._codRotacion = value;
					this.SendPropertyChanged("codRotacion");
					this.OncodRotacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> fechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				if ((this._fechaInicio != value))
				{
					this.OnfechaInicioChanging(value);
					this.SendPropertyChanging();
					this._fechaInicio = value;
					this.SendPropertyChanged("fechaInicio");
					this.OnfechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinal", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFinal
		{
			get
			{
				return this._fechaFinal;
			}
			set
			{
				if ((this._fechaFinal != value))
				{
					this.OnfechaFinalChanging(value);
					this.SendPropertyChanging();
					this._fechaFinal = value;
					this.SendPropertyChanged("fechaFinal");
					this.OnfechaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRotacion_tbRotacionUsuario", Storage="_tbRotacionUsuario", ThisKey="codRotacion", OtherKey="codRotacion")]
		public EntitySet<tbRotacionUsuario> tbRotacionUsuario
		{
			get
			{
				return this._tbRotacionUsuario;
			}
			set
			{
				this._tbRotacionUsuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbRotacionUsuario(tbRotacionUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tbRotacion = this;
		}
		
		private void detach_tbRotacionUsuario(tbRotacionUsuario entity)
		{
			this.SendPropertyChanging();
			entity.tbRotacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbRotacionUsuario")]
	public partial class tbRotacionUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codRotacion;
		
		private int _codUsuario;
		
		private System.Nullable<bool> _estado;
		
		private EntityRef<tbRotacion> _tbRotacion;
		
		private EntityRef<tbUsuario> _tbUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodRotacionChanging(int value);
    partial void OncodRotacionChanged();
    partial void OncodUsuarioChanging(int value);
    partial void OncodUsuarioChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public tbRotacionUsuario()
		{
			this._tbRotacion = default(EntityRef<tbRotacion>);
			this._tbUsuario = default(EntityRef<tbUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRotacion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codRotacion
		{
			get
			{
				return this._codRotacion;
			}
			set
			{
				if ((this._codRotacion != value))
				{
					if (this._tbRotacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodRotacionChanging(value);
					this.SendPropertyChanging();
					this._codRotacion = value;
					this.SendPropertyChanged("codRotacion");
					this.OncodRotacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codUsuario
		{
			get
			{
				return this._codUsuario;
			}
			set
			{
				if ((this._codUsuario != value))
				{
					if (this._tbUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._codUsuario = value;
					this.SendPropertyChanged("codUsuario");
					this.OncodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRotacion_tbRotacionUsuario", Storage="_tbRotacion", ThisKey="codRotacion", OtherKey="codRotacion", IsForeignKey=true)]
		public tbRotacion tbRotacion
		{
			get
			{
				return this._tbRotacion.Entity;
			}
			set
			{
				tbRotacion previousValue = this._tbRotacion.Entity;
				if (((previousValue != value) 
							|| (this._tbRotacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbRotacion.Entity = null;
						previousValue.tbRotacionUsuario.Remove(this);
					}
					this._tbRotacion.Entity = value;
					if ((value != null))
					{
						value.tbRotacionUsuario.Add(this);
						this._codRotacion = value.codRotacion;
					}
					else
					{
						this._codRotacion = default(int);
					}
					this.SendPropertyChanged("tbRotacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUsuario_tbRotacionUsuario", Storage="_tbUsuario", ThisKey="codUsuario", OtherKey="codUsuario", IsForeignKey=true)]
		public tbUsuario tbUsuario
		{
			get
			{
				return this._tbUsuario.Entity;
			}
			set
			{
				tbUsuario previousValue = this._tbUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tbUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbUsuario.Entity = null;
						previousValue.tbRotacionUsuario.Remove(this);
					}
					this._tbUsuario.Entity = value;
					if ((value != null))
					{
						value.tbRotacionUsuario.Add(this);
						this._codUsuario = value.codUsuario;
					}
					else
					{
						this._codUsuario = default(int);
					}
					this.SendPropertyChanged("tbUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSalida")]
	public partial class tbSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codSalida;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaSalida;
		
		private EntitySet<tbDetalleSalida> _tbDetalleSalida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodSalidaChanging(int value);
    partial void OncodSalidaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaSalidaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaSalidaChanged();
    #endregion
		
		public tbSalida()
		{
			this._tbDetalleSalida = new EntitySet<tbDetalleSalida>(new Action<tbDetalleSalida>(this.attach_tbDetalleSalida), new Action<tbDetalleSalida>(this.detach_tbDetalleSalida));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSalida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codSalida
		{
			get
			{
				return this._codSalida;
			}
			set
			{
				if ((this._codSalida != value))
				{
					this.OncodSalidaChanging(value);
					this.SendPropertyChanging();
					this._codSalida = value;
					this.SendPropertyChanged("codSalida");
					this.OncodSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalida", DbType="Date")]
		public System.Nullable<System.DateTime> fechaSalida
		{
			get
			{
				return this._fechaSalida;
			}
			set
			{
				if ((this._fechaSalida != value))
				{
					this.OnfechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._fechaSalida = value;
					this.SendPropertyChanged("fechaSalida");
					this.OnfechaSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSalida_tbDetalleSalida", Storage="_tbDetalleSalida", ThisKey="codSalida", OtherKey="codSalida")]
		public EntitySet<tbDetalleSalida> tbDetalleSalida
		{
			get
			{
				return this._tbDetalleSalida;
			}
			set
			{
				this._tbDetalleSalida.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetalleSalida(tbDetalleSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbSalida = this;
		}
		
		private void detach_tbDetalleSalida(tbDetalleSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbSalida = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTipoSangre")]
	public partial class tbTipoSangre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codTipoSangre;
		
		private string _tipoSangre;
		
		private EntitySet<tbPaciente> _tbPaciente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodTipoSangreChanging(int value);
    partial void OncodTipoSangreChanged();
    partial void OntipoSangreChanging(string value);
    partial void OntipoSangreChanged();
    #endregion
		
		public tbTipoSangre()
		{
			this._tbPaciente = new EntitySet<tbPaciente>(new Action<tbPaciente>(this.attach_tbPaciente), new Action<tbPaciente>(this.detach_tbPaciente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoSangre", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codTipoSangre
		{
			get
			{
				return this._codTipoSangre;
			}
			set
			{
				if ((this._codTipoSangre != value))
				{
					this.OncodTipoSangreChanging(value);
					this.SendPropertyChanging();
					this._codTipoSangre = value;
					this.SendPropertyChanged("codTipoSangre");
					this.OncodTipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(15)")]
		public string tipoSangre
		{
			get
			{
				return this._tipoSangre;
			}
			set
			{
				if ((this._tipoSangre != value))
				{
					this.OntipoSangreChanging(value);
					this.SendPropertyChanging();
					this._tipoSangre = value;
					this.SendPropertyChanged("tipoSangre");
					this.OntipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbTipoSangre_tbPaciente", Storage="_tbPaciente", ThisKey="codTipoSangre", OtherKey="codTipoSangre")]
		public EntitySet<tbPaciente> tbPaciente
		{
			get
			{
				return this._tbPaciente;
			}
			set
			{
				this._tbPaciente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPaciente(tbPaciente entity)
		{
			this.SendPropertyChanging();
			entity.tbTipoSangre = this;
		}
		
		private void detach_tbPaciente(tbPaciente entity)
		{
			this.SendPropertyChanging();
			entity.tbTipoSangre = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCategoria")]
	public partial class tbCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codCategoria;
		
		private string _categoria;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodCategoriaChanging(int value);
    partial void OncodCategoriaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public tbCategoria()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(50)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbProducto", ThisKey="codCategoria", OtherKey="codCategoria")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPresentacion")]
	public partial class tbPresentacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPresentacion;
		
		private string _presentacion;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPresentacionChanging(int value);
    partial void OncodPresentacionChanged();
    partial void OnpresentacionChanging(string value);
    partial void OnpresentacionChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public tbPresentacion()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presentacion", DbType="VarChar(50)")]
		public string presentacion
		{
			get
			{
				return this._presentacion;
			}
			set
			{
				if ((this._presentacion != value))
				{
					this.OnpresentacionChanging(value);
					this.SendPropertyChanging();
					this._presentacion = value;
					this.SendPropertyChanged("presentacion");
					this.OnpresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProducto", Storage="_tbProducto", ThisKey="codPresentacion", OtherKey="codPresentacion")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = null;
		}
	}
	
	public partial class LogiarResult
	{
		
		private int _codUsuario;
		
		private int _codTipoUsuario;
		
		private string _usuario;
		
		private string _password;
		
		public LogiarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuario", DbType="Int NOT NULL")]
		public int codUsuario
		{
			get
			{
				return this._codUsuario;
			}
			set
			{
				if ((this._codUsuario != value))
				{
					this._codUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoUsuario", DbType="Int NOT NULL")]
		public int codTipoUsuario
		{
			get
			{
				return this._codTipoUsuario;
			}
			set
			{
				if ((this._codTipoUsuario != value))
				{
					this._codTipoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
